language: node_js
node_js: stable
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --install-recommends winehq-stable
install: npm install

jobs:
  include:
    - stage: tests
      node_js: stable
      script:
        - npm run test
    - stage: semantic release
      if: branch = master AND type = push
      node_js: stable
      script:
        - npm run release
        - npm run semantic-release
